# Generated by Django 4.2.30 on 2026-05-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='matricula',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
