# Generated by Django 4.2.30 on 2026-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='materias',
            field=models.ManyToManyField(blank=True, to='alumnos.materia'),
        ),
    ]
