# Generated by Django 4.2.30 on 2026-06-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alter_alumno_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
