# Generated by Django 4.2.30 on 2026-06-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_materia_hora_fin_materia_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='dia',
            field=models.CharField(blank=True, choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10, null=True),
        ),
    ]
