# Generated by Django 4.2.30 on 2026-05-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0005_remove_alumno_materias_alumno_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='materias',
            field=models.ManyToManyField(blank=True, to='alumnos.materia'),
        ),
    ]
