# Generated by Django 4.2.30 on 2026-05-22 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_alumno_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='user',
        ),
    ]
