# Generated by Django 4.2.30 on 2026-06-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_horario_materia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horario_materia',
            new_name='Horario',
        ),
    ]
