# Generated by Django 4.2.30 on 2026-06-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0008_materia_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='parcial',
            field=models.IntegerField(choices=[(1, 'Parcial 1'), (2, 'Parcial 2'), (3, 'Parcial 3')], default=1),
            preserve_default=False,
        ),
    ]
