# Generated by Django 4.2.30 on 2026-06-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_calificacion_parcial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial', models.IntegerField(choices=[(1, 'Parcial 1'), (2, 'Parcial 2'), (3, 'Parcial 3')], unique=True)),
                ('habilitado', models.BooleanField(default=False)),
            ],
        ),
    ]
