# Generated by Django 4.2.30 on 2026-06-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0010_configuracionparcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='regularizacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('alumno', 'materia', 'parcial')},
        ),
    ]
