# Generated by Django 4.2.30 on 2026-06-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0011_calificacion_regularizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRegularizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=False)),
            ],
        ),
    ]
